# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saif Ahmed Kayani
title: Software Engineer | Implementation and Support Engineer
email: saifahmedkayani@gmail.com
phone: +92 332 9966275
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  saif-ahmad-k
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: saif-ahmad-k
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Picsart_23-03-12_14-50-48-393.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! Through out my career, I've worked as an Integration Engineer, developer, SQA and Support Engineer. This is because I love learning new technologies and providing solutions using modern technology. I have been part of Digital Financial Systems, Transmission & ERP teams and worked on different stages in SDLC. I enjoy working on databases and performing analysis. I also have exposure in interfacing systems to another and writing automated scripts be it in bash/python/c#.
  I am most skilled in: <mark>SQL</mark> and <mark>Automation scripting</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Digitata Networks
        link: digitatanetworks.com
        # link_text: boringcompany.com
        sub_title: Implementation and Support Engineer
        caption: October 2021 - Present
        quote: >
        description: | # this will include new lines to allow paragraphs
            "Integrate and install solutions on the customers test and production environments. Develop new application integrations and provide daily operational support. Performed hands-on technical implementation, troubleshooting, and remediation on complex client projects. Troubleshoot and diagnose customer reported issues on the different levels of solutions (i.e. Database, Application, Network, Communication, and Integration Interfaces Levels). Writing and reviewing testing plans and creating test plan automation procedures. Creating automation scripts (bash/python). Working on the product design phase and gathering data. Applying technical skills related to the product being tested (knowledge of programming languages to software QA)."

      - layout: left
        title: Mobilink Microfinance Bank
        link: Jazz.com
        # link_text: boringcompany.com
        sub_title: Alternate Delivery Channels Executive
        caption:  September 2018 - October 2021
        quote: >
        description: | # this will include new lines to allow paragraphs
            "Provide support for all applications on all Production Systems.	Deployments and integration on all Production Systems. Performing User Acceptance Testing & System Integration Testing of all patches and releases. Management of Servers Configuration of new ADC terminals & deployment of new products. Database Scripting (Oracle, SQL). Responsible for training internal unit staff to ensure that primary and backup resources are available. Monitor & update of Channel operations. Coordinate with I.T/Vendor/Business for a smooth operation."
			
	  - layout: left
        title: Webtech/Extend.se
        link: webtech.com
        # link_text: boringcompany.com
        sub_title: Junior Developer
        caption:  March 2018 - September 2018
        quote: >
        description: | # this will include new lines to allow paragraphs
            "NET Development, Database Development & Application Deployments. XML Mapping and Parsing"

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arid University
        caption: 2013 - 2017
        sub_title: BS Computer Science
        quote: >
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university.

  - title: Some additional Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Integration and support some of my other skills include:
      - QA Testing tools â€“ Selenium, JMeter
      - Database Operations - MS SQL, DynamoDB, Oracle, MySql, Elastic Search, Postgres
      - Scripting - PowerShell, CMD, Linux RHEL
      - Programming - C#, VB, SQL, HTML, Python
	  - Software Versioning Control - TFS, JIRA, Git, Fork
      - Business Intelligence - PowerBI, Microsoft Excel, Anaconda Python
      - Server Management - Synchronization, Archiving, Storage Management
	  - Documentation - User Manuals, Test Cases, UATs, SITs
	  - Other Tools - VS, PyCharm, AWS Management Console, ComponentOne, Altova Mapforce


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
